version: "3.8"
services:

#  should be launched apart
  data-integration:
    build:
      context: ./data-integration
    volumes:
      - data:/data-integration/data
    env_file:
      .env-db

volumes:
  db-data:
  data:
